/*Copyright (c), 2010, Sanford, L.P. All Rights Reserved.*/(function() {function h(a){throw a;}var j=true,k=null,l=false,m=this;function n(a,b,c){a=a.split(".");c=c||m;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}}Math.floor(Math.random()*2147483648).toString(36);var p={};n("dymo.label.framework.FlowDirection",p,void 0);p.LeftToRight="LeftToRight";p.RightToLeft="RightToLeft";var q={};n("dymo.label.framework.LabelWriterPrintQuality",q,void 0);q.Auto="Auto";q.Text="Text";q.BarcodeAndGraphics="BarcodeAndGraphics";var r={};n("dymo.label.framework.TwinTurboRoll",r,void 0);r.Auto="Auto";r.Left="Left";r.Right="Right";var s={};n("dymo.label.framework.TapeAlignment",s,void 0);s.Center="Center";s.Left="Left";s.Right="Right";var t={};
n("dymo.label.framework.TapeCutMode",t,void 0);t.AutoCut="AutoCut";t.ChainMarks="ChainMarks";var v={};n("dymo.label.framework.AddressBarcodePosition",v,void 0);v.AboveAddress="AboveAddress";v.BelowAddress="BelowAddress";v.Suppress="Suppress";function w(a){if(typeof DOMParser!="undefined")return(new DOMParser).parseFromString(a,"application/xml");else if(typeof ActiveXObject!="undefined"){var b=new ActiveXObject("MSXML2.DOMDocument");b.loadXML(a);return b}else{b=new XMLHttpRequest;b.open("GET","data:text/xml;charset=utf-8,"+encodeURIComponent(a),l);b.send(k);return b.responseXML}}
function x(a){if(typeof XMLSerializer!="undefined")return(new XMLSerializer).serializeToString(a);else if(a.xml)return a.xml;else h(Error("XML.serialize is not supported or can't serialize "+a))}function y(a,b,c,d){b=a.ownerDocument.createElement(b);c&&b.appendChild(a.ownerDocument.createTextNode(c));if(d)for(var e in d)b.setAttribute(e,d[e]);a.appendChild(b);return b}
function B(a){if(!a)return"";for(var b="",c=0;c<a.childNodes.length;c++)if(a.childNodes[c].nodeType==3)b+=a.childNodes[c].data;return b}function C(a,b){D(a);a.appendChild(a.ownerDocument.createTextNode(b))}function D(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
function E(a,b,c){this.l=b;this.namespaces=c;var d=a.ownerDocument;if(d==k)d=a;if(d.createExpression)this.i=d.createExpression(b,function(f){return c[f]});else{this.f="";if(c!=k)for(var e in c){if(this.f)this.f+=" ";this.f+="xmlns:"+e+'="'+c[e]+'"'}}}
function F(a,b,c){var d;b=new E(a,b,c||k);a=a;if(b.i){for(var e=b.i.evaluate(a,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,k),f=Array(e.snapshotLength),g=0;g<e.snapshotLength;g++)f[g]=e.snapshotItem(g);d=f}else try{var i=a.ownerDocument;if(i==k)i=a;try{i.setProperty("SelectionLanguage","XPath")}catch(o){}try{i.setProperty("SelectionNamespaces",b.f)}catch(u){}if(a==i)a=i.documentElement;e=a.selectNodes(b.l);f=Array(e.length);for(g=0;g<e.length;g++)f[g]=e[g];d=f}catch(z){h("XPath not supported by this browser.: "+
z)}return d}function G(a,b,c){var d;b=new E(a,b,c||k);a=a;if(b.i)d=b.i.evaluate(a,XPathResult.FIRST_ORDERED_NODE_TYPE,k).singleNodeValue;else try{var e=a.ownerDocument;if(e==k)e=a;try{e.setProperty("SelectionLanguage","XPath")}catch(f){}try{e.setProperty("SelectionNamespaces",b.f)}catch(g){}if(a==e)a=e.documentElement;d=a.selectSingleNode(b.l)}catch(i){h("XPath not supported by this browser.: "+i)}return d};function H(a,b,c,d,e){this.printerType=a;this.name=b;this.modelName=c;this.isConnected=d;this.isLocal=e}function I(a,b,c,d,e){H.call(this,"LabelWriterPrinter",a,b,c,d);this.isTwinTurbo=e}function aa(a,b,c,d,e){H.call(this,"TapePrinter",a,b,c,d);this.isAutoCutSupported=e};function J(){this.k=[]}n("dymo.label.framework.LabelSetBuilder",J,void 0);J.prototype.t=function(){return this.k};J.prototype.getRecords=J.prototype.t;J.prototype.m=function(){var a=new K;this.k.push(a);return a};J.prototype.addRecord=J.prototype.m;
function L(a){for(var b=w("<LabelSet/>"),c=b.documentElement,d=0;d<a.length;d++){var e=a[d],f=b.createElement("LabelRecord"),g;for(g in e){var i=e[g];if(typeof i!="function"){i=i.toString();var o=b.createElement("ObjectData");o.setAttribute("Name",g);if(i.indexOf("<TextMarkup>")==0){i=w(i);o.appendChild(i.documentElement.cloneNode(j))}else o.appendChild(b.createTextNode(i));f.appendChild(o)}}c.appendChild(f)}return x(b)}J.toXml=L;J.prototype.toString=function(){return L(this.k)};function K(){}
K.prototype.C=function(a,b){b=b.toString();if(b.indexOf("<TextMarkup>")!=0)b="<TextMarkup>"+b+"</TextMarkup>";this[a]=b;return this};K.prototype.setTextMarkup=K.prototype.C;K.prototype.B=function(a,b){this[a]=b;return this};K.prototype.setText=K.prototype.B;K.prototype.z=function(a,b){this[a]=b;return this};K.prototype.setBase64Image=K.prototype.z;function M(a){this.j=w(a)}M.prototype.h=function(){return x(this.j)};M.prototype.getLabelXml=M.prototype.h;M.prototype.u=function(a,b){return N(this.h(),a,b)};M.prototype.render=M.prototype.u;M.prototype.print=function(a,b,c){O(a,b,this.h(),c)};M.prototype.print=M.prototype.print;function P(a){return F(a.j,"//AddressObject|//TextObject|//BarcodeObject|//ShapeObject|//CounterObject|//ImageObject|//CircularTextObject|//DateTimeObject")}
M.prototype.q=function(){for(var a=P(this),b=[],c=0;c<a.length;c++)b.push(B(G(a[c],"Name")));return b};M.prototype.getObjectNames=M.prototype.q;function Q(a){return F(a.j,"//AddressObject")}M.prototype.o=function(){return Q(this).length};M.prototype.getAddressObjectCount=M.prototype.o;M.prototype.n=function(a){return B(G(Q(this)[a],"BarcodePosition"))};M.prototype.getAddressBarcodePosition=M.prototype.n;
M.prototype.v=function(a,b){if(!(b=="AboveAddress"||b=="BelowAddress"||b=="Suppress"))h(Error("verifyAddressBarcodePosition(): barcode position '"+b+"' is invalid value"));C(G(Q(this)[a],"BarcodePosition"),b);return this};M.prototype.setAddressBarcodePosition=M.prototype.v;M.prototype.p=function(a){return R(this,Q(this)[a])};M.prototype.getAddressText=M.prototype.p;M.prototype.w=function(a,b){return S(this,Q(this)[a],b)};M.prototype.setAddressText=M.prototype.w;
function T(a,b){for(var c=P(a),d=0;d<c.length;d++){var e=c[d];if(B(G(e,"Name"))==b)return e}h(Error("getObjectByNameElement(): no object with name '"+b+"' was found"))}function R(a,b){for(var c=F(b,"StyledText/Element/String//text()"),d="",e=0;e<c.length;e++)d+=c[e].data;return d}
M.prototype.s=function(a){a=T(this,a);switch(a.tagName){case "AddressObject":case "TextObject":return R(this,a);case "BarcodeObject":return B(G(a,"Text",k));case "ImageObject":if(a=G(a,"Image",k))return B(a);else break;case "CircularTextObject":return B(G(a,"Text",k))}return""};M.prototype.getObjectText=M.prototype.s;
function S(a,b,c){for(var d=G(b,"StyledText"),e=[],f=F(d,"Element"),g=0;g<f.length;g++){var i=f[g],o=B(G(i,"String")).split("\n").length;g>0&&o--;i=G(i,"Attributes");for(var u=0;u<o;u++)e.push(i)}b=F(b,"LineFonts/Font");var z;if(b.length==0)z=w('<Font Family="Arial" Size="12" Bold="False" Italic="False" Underline="False" Strikeout="False" />').documentElement;f=w('<ForeColor Alpha="255" Red="0" Green="0" Blue="0" />').documentElement;D(d);c=c.split("\n");for(g=0;g<c.length;g++){var A=c[g].replace("\r",
"");if(g<c.length-1)A+="\n";o=z;if(g<b.length)o=b[g];else if(b.length>0)o=b[b.length-1];i=f;if(g<e.length)i=G(e[g],"ForeColor");u=d.ownerDocument.createElement("Element");var U=d.ownerDocument.createElement("String");C(U,A);A=d.ownerDocument.createElement("Attributes");A.appendChild(o.cloneNode(j));A.appendChild(i.cloneNode(j));u.appendChild(U);u.appendChild(A);d.appendChild(u)}return a}
M.prototype.A=function(a,b){var c=T(this,a);switch(c.tagName){case "AddressObject":S(this,c,b);break;case "TextObject":c=G(c,"StyledText");var d=G(c,"Element");if(d){D(c);C(G(d,"String"),b);c.appendChild(d)}else{d=w("<Element><String>"+b+'</String>                    <Attributes>                        <Font Family="Arial" Size="12" Bold="False" Italic="False" Underline="False" Strikeout="False" />                        <ForeColor Alpha="255" Red="0" Green="0" Blue="0" />                    </Attributes></Element>');
c.appendChild(d.documentElement.cloneNode(j))}break;case "BarcodeObject":C(G(c,"Text"),b);break;case "ImageObject":if(d=G(c,"Image",k))C(d,b);else{var e=G(c,"ImageLocation",k);if(!e)h(Error("setObjectText(): <ImageLocation> is expected but not found: "+x(d)));d=e.ownerDocument.createElement("Image");C(d,b);c.replaceChild(d,e)}break;case "CircularTextObject":C(G(c,"Text",k),b);break;case "DateTimeObject":C(G(c,"PreText",k),b);break;case "CounterObject":C(G(c,"PreText",k),b)}return this};
M.prototype.setObjectText=M.prototype.A;M.prototype.toString=function(){return this.h()};n("dymo.label.framework.VERSION","1.0",void 0);function ba(a,b,c){this.isBrowserSupported=a;this.isFrameworkInstalled=b;this.errorDetails=c}
function V(){var a={d:l,e:l,c:""},b=window.navigator.platform;if(b.indexOf("Win")!=-1)if(typeof ActiveXObject!="undefined"){a.d=j;try{if(typeof new ActiveXObject("DYMOLabelFrameworkIEPlugin.Plugin")!="object")a.c="Unable to create DYMO.Label.Framework ActiveX object. Check that DYMO.Label.Framework is installed";else a.e=j}catch(c){a.c="Unable to create DYMO.Label.Framework ActiveX object. Check that DYMO.Label.Framework is installed. Exception details: "+c}}else{a.d=j;b=l;for(var d=0;d<navigator.plugins.length;++d){for(var e=
navigator.plugins[d],f=0;f<e.length;++f)if(e[f].type=="application/x-dymolabel"){b=j;break}if(b)break}if(b)a.e=j;else a.c="DYMO Label Framework Plugin is not installed"}else if(b.indexOf("Mac")!=-1)if(navigator.userAgent.indexOf("Safari")!=-1&&navigator.vendor.indexOf("Apple")!=-1){a.d=j;b=l;for(d=0;d<navigator.plugins.length;++d){e=navigator.plugins[d];for(f=0;f<e.length;++f)if(e[f].type=="application/x-dymolabel"){b=j;break}if(b)break}if(b)if(W().GetAPIVersion()>="2.0")a.e=j;else a.c="DYMO Label Safari Plugin is installed but outdated. Install latest version.";
else a.c="DYMO Label Safari Plugin is not installed"}else{a.d=j;b=l;for(d=0;d<navigator.plugins.length;++d){e=navigator.plugins[d];for(f=0;f<e.length;++f)if(e[f].type=="application/x-npapi-dymolabel"){b=j;break}if(b)break}if(b)a.e=j;else a.c="DYMO Label NPAPI Plugin is not installed"}else a.c="The operating system is not supported";return new ba(a.d,a.e,a.c)}n("dymo.label.framework.checkEnvironment",V,void 0);
function W(){if(!document.getElementById("_DymoLabelFrameworkJslSafariPlugin")){var a=document.createElement("embed");a.type="application/x-dymolabel";a.id="_DymoLabelFrameworkJslSafariPlugin";a.width=1;a.height=1;a.hidden=j;document.body.appendChild(a)}return window._DymoLabelFrameworkJslSafariPlugin}
function ca(){if(!document.getElementById("_DymoLabelFrameworkJslPlugin")){var a=document.createElement("embed");a.type="application/x-dymolabel";a.id="_DymoLabelFrameworkJslPlugin";a.width=1;a.height=1;a.hidden=j;document.body.appendChild(a)}return document.getElementById("_DymoLabelFrameworkJslPlugin")}
function da(){if(!document.getElementById("_DymoLabelFrameworkJslPlugin")){var a=document.createElement("embed");a.type="application/x-npapi-dymolabel";a.id="_DymoLabelFrameworkJslPlugin";a.width=1;a.height=1;a.hidden=j;document.body.appendChild(a)}return document.getElementById("_DymoLabelFrameworkJslPlugin")}
function ea(){var a=new ActiveXObject("DYMOLabelFrameworkIEPlugin.Plugin");if(typeof a!="object")h(Error("createFramework(): unable to create DYMO.Label.Framework object. Check DYMO Label Framework is installed"));return a}var X;
function Y(){if(!X){var a=V();if(a.errorDetails!="")h(Error(a.errorDetails));if(typeof ActiveXObject!="undefined"){X={};var b=ea();X.getPrinters=function(){return b.GetPrinters()};X.openLabelFile=function(e){return b.OpenLabelFile(e)};X.printLabel=function(e,f,g,i){b.PrintLabel(e,f,g,i)};X.renderLabel=function(e,f,g){return b.RenderLabel(e,f,g)};X.loadImageAsPngBase64=function(e){return b.LoadImageAsPngBase64(e)}}else if(navigator.platform.indexOf("Win")!=-1){var c=ca();if(c){X={};X.getPrinters=function(){return c.getPrinters()};
X.openLabelFile=function(e){return c.openLabelFile(e)};X.printLabel=function(e,f,g,i){c.printLabel(e,f,g,i)};X.renderLabel=function(e,f,g){return c.renderLabel(e,f,g)};X.loadImageAsPngBase64=function(e){return c.loadImageAsPngBase64(e)}}else h(Error("DYMO Label Framework is not installed"))}else{var d;if(d=navigator.userAgent.indexOf("Safari")!=-1&&navigator.vendor.indexOf("Apple")!=-1?W():da()){X={};X.getPrinters=function(){return d.getPrinters()};X.openLabelFile=function(e){var f=d.openLabelFile(e);
if(!f)h(Error("Unable to open label file '"+e+"'"));return f};X.printLabel=function(e,f,g,i){d.printLabel(g,e,f,i)};X.renderLabel=function(e,f,g){return d.renderLabel(e,f,g)};X.loadImageAsPngBase64=function(e){var f=d.loadImageAsPngBase64(e);if(!f)h(Error("Unable to load image from uri '"+e+"'"));return f}}else h(Error("DYMO Label Framework is not installed"))}}return X}
function Z(){function a(u,z){return u.getElementsByTagName(z)[0].firstChild.data}var b=Y().getPrinters(),c=[],d=w(b).getElementsByTagName("Printers")[0];b=d.getElementsByTagName("LabelWriterPrinter");for(var e=0;e<b.length;e++){var f=a(b[e],"Name"),g=a(b[e],"ModelName"),i=a(b[e],"IsConnected")=="True",o=a(b[e],"IsLocal")=="True";f=new I(f,g,i,o,a(b[e],"IsTwinTurbo")=="True");c[e]=f;c[f.name]=f}d=d.getElementsByTagName("TapePrinter");for(e=0;e<d.length;e++){f=a(d[e],"Name");g=a(d[e],"ModelName");i=
a(d[e],"IsConnected")=="True";o=a(d[e],"IsLocal")=="True";f=new aa(f,g,i,o,a(d[e],"IsAutoCutSupported")=="True");c[e+b.length]=f;c[f.name]=f}return c}n("dymo.label.framework.getPrinters",Z,void 0);function $(a){for(var b=[],c=Z(),d=0;d<c.length;d++){var e=c[d];e.printerType==a&&b.push(e)}return b}n("dymo.label.framework.getLabelWriterPrinters",function(){return $("LabelWriterPrinter")},void 0);n("dymo.label.framework.getTapePrinters",function(){return $("TapePrinter")},void 0);
n("dymo.label.framework.openLabelFile",function(a){return new M(Y().openLabelFile(a))},void 0);n("dymo.label.framework.openLabelXml",function(a){return new M(a)},void 0);function O(a,b,c,d){b=b||"";d=d||"";if(typeof d!="string")d=d.toString();if(typeof c=="undefined")h(Error("printLabel(): labelXml parameter should be specified"));if(typeof c!="string")c=c.toString();Y().printLabel(a,b,c,d)}n("dymo.label.framework.printLabel",O,void 0);
function N(a,b,c){if(typeof a=="undefined")h(Error("renderLabel(): labelXml parameter should be specified"));if(typeof a!="string")a=a.toString();return Y().renderLabel(a,b||"",c||"")}n("dymo.label.framework.renderLabel",N,void 0);n("dymo.label.framework.loadImageAsPngBase64",function(a){return Y().loadImageAsPngBase64(a)},void 0);
n("dymo.label.framework.createLabelWriterPrintParamsXml",function(a){if(!a)return"";var b=w("<LabelWriterPrintParams/>"),c=b.documentElement;a.copies&&y(c,"Copies",a.copies.toString());a.jobTitle&&y(c,"JobTitle",a.jobTitle);a.flowDirection&&y(c,"FlowDirection",a.flowDirection);a.printQuality&&y(c,"PrintQuality",a.printQuality);a.twinTurboRoll&&y(c,"TwinTurboRoll",a.twinTurboRoll);return x(b)},void 0);
n("dymo.label.framework.createTapePrintParamsXml",function(a){if(!a)return"";var b=w("<TapePrintParams/>"),c=b.documentElement;a.copies&&y(c,"Copies",a.copies.toString());a.jobTitle&&y(c,"JobTitle",a.jobTitle);a.flowDirection&&y(c,"FlowDirection",a.flowDirection);a.alignment&&y(c,"Alignment",a.alignment);a.cutMode&&y(c,"CutMode",a.cutMode);return x(b)},void 0);
n("dymo.label.framework.createLabelRenderParamsXml",function(a){function b(e,f){y(d,e,undefined,{Alpha:f.a||f.alpha||255,Red:f.r||f.red||0,Green:f.g||f.green||0,Blue:f.b||f.blue||0})}if(!a)return"";var c=w("<LabelRenderParams/>"),d=c.documentElement;a.labelColor&&b("LabelColor",a.labelColor);a.shadowColor&&b("ShadowColor",a.shadowColor);typeof a.shadowDepth!="undefined"&&y(d,"ShadowDepth",a.shadowDepth.toString());a.flowDirection&&y(d,"FlowDirection",a.flowDirection);if(typeof a.pngUseDisplayResolution!=
"undefined")y(d,"PngUseDisplayResolution",a.pngUseDisplayResolution?"True":"False");return x(c)},void 0);})();
